name: Robot-Say-Hello          # ชื่อของหุ่นยนต์ตัวนี้
on: [push]                     # สั่งให้หุ่นยนต์ทำงานทันทีที่เรา "ส่งของ" (Push) ขึ้นไป

jobs:
  build:                       # งานที่หุ่นยนต์ต้องทำ
    runs-on: ubuntu-latest     # สั่งให้หุ่นยนต์ทำงานในห้องทดลองสุดไฮเทค
    steps:
      - name: Say Hello        # ขั้นแรก: ตั้งชื่อการกระทำ
        run: echo "Hello, World!" # สั่งให้หุ่นยนต์ตะโกนคำว่า Hello, World! ออกมา