name: Deploy-Web-To-GitHub-Pages
on: [push]

# 🔑 แจกคีย์การ์ดสิทธิ์การเขียนไฟล์ให้หุ่นยนต์
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 📦 1. ใช้ตัวดึงโค้ดมาตรฐานสากล + ตั้งชื่อเป็น ชื่อและรหัสของน้องตามโจทย์!
      - name: Yotsaphon-024
        uses: actions/checkout@v4

      # 🚀 2. สั่งหุ่นยนต์ตัวจริง (peaceiris) โยนไฟล์ขึ้นระบบตั้งโชว์
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # ให้กุญแจวิเศษกับหุ่นยนต์ไปทำงาน
          publish_dir: ./                            # เอาไฟล์ทั้งหมดในกล่องนี้ไปโชว์
